{{ morning_output }}: {{ parts_deps_list }}
	ffmpeg -y -i "concat:{{ parts_concat_list }}" -c copy {{ morning_output }}

{% for part in parts %}
# {{ part.timestamp }}
{{ part.filename }}: {{ morning_input }}.delayed.ts
	ffmpeg -y -ss {{ part.begin }} -i {{ morning_input }}.delayed.ts -t {{ part.length }} -c copy {{ part.filename }}
{% endfor %}

{{ morning_input }}.delayed.ts: {{ morning_input }}.fixed.ts
	ffmpeg -y -i "{{ morning_input }}.fixed.ts" -itsoffset -0.30 -i "{{ morning_input }}.fixed.ts" -map 1:v -map 0:a -vcodec copy -acodec copy "{{ morning_input }}.delayed.ts"

{{ morning_input }}.fixed.ts: {{ morning_input }}
	ffmpeg -y -i {{ morning_input }} -codec copy -bsf:v h264_mp4toannexb {{ morning_input }}.fixed.ts
